name: escola

services:
  backend:
    build:
      context: .
      dockerfile: ./Dockerfile
    container_name: ${SPRING_APPLICATION_NAME}
    ports:
      - "${MODULO_SERVICE_PORT}:${MODULO_SERVICE_PORT}"
      - "${MODULO_SERVICE_DEBUG_PORT}:${MODULO_SERVICE_DEBUG_PORT}"
    volumes:
      - .:/app
      - uploads:/app/uploads
    env_file:
      - ./.env
    networks:
      - escola_escola-network

  fakemail-escola:
    container_name: fakemail-escola
    image: gessnerfl/fake-smtp-server:latest
    restart: no
    networks:
      - escola_escola-network
    ports:
      - "5080:8080"
      - "8025:8025"

networks:
  escola_escola-network:
    external: true

volumes:
  # Define um volume nomeado para ser usado pelos contêineres.
  uploads:
